wandb_version: 1

batch_size:
  desc: null
  value: 1
img_size:
  desc: null
  value: 512
epochs:
  desc: null
  value: 10
num_classes:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.005
model_name:
  desc: null
  value: fasterrcnn
_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721446512
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      - 80
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.8.19
      5: 0.17.3
      8:
      - 5
      13: linux-x86_64
